apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubetask.fullname" . }}-agent
  namespace: {{ include "kubetask.namespace" . }}
  labels:
    {{- include "kubetask.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubetask.fullname" . }}-agent
subjects:
- kind: ServiceAccount
  name: {{ include "kubetask.agent.serviceAccountName" . }}
  namespace: {{ include "kubetask.namespace" . }}
