apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubetask.controller.serviceAccountName" . }}
  namespace: {{ include "kubetask.namespace" . }}
  labels:
    {{- include "kubetask.controller.labels" . | nindent 4 }}
  {{- with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
